name: First action

on:
  push:
    branches:
      - main
      - limbu_first
        
  jobs:
     first-action:
       runs-on: ubuntu-latest
       steps:
       - name: echo
         run: |
           echo "Hello Earth"        
