name: First action

on:
  push:
    branches:
      - main
      - limbu_first
        
jobs:
   first-action:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2        
     - name: echo
       run: |
         chmod +x ./make.sh
         ls -l
         touch file.txt
         ls -l        
